language: go

jobs:
  include:
  - stage: test
    go: 1.13.x
    script:
      - go test ./...
  - stage: Build and Deploy
    go: 1.13.x
    script:
      - export SOURCE_DATE_EPOCH=$(git show -s --format=%ci ${TRAVIS_TAG:-${TRAVIS_COMMIT}}^{commit})
      - go build github.com/terinjokes/bakelite
      - "./bakelite -ldflags='-s -w' github.com/terinjokes/bakelite"
      - for i in bakelite-*; do tar --mtime="${SOURCE_DATE_EPOCH}" --owner=0 --group=0 --numeric-owner -c $i | gzip -n - > $i.tar.gz; done
      - shasum -a 512 bakelite-*.tar.gz | tee sha512sum.txt
    deploy:
      provider: releases
      token:
        secure: vZMPoI0umyg3AR5C9BSsfI0LyvnMivFLUsgwoCKvfSoqDHf3Q8rQvSsvSYqCkZ3zJY4KoAhq/oAPdXRmwYWD3l9RQxnHt8od2cvzZOJISTBWwBKqj9TjXPrVjPy+9zAHtsk4E6jISaWpj9qka4KVwyfvsCOgPs2E7MZ6tMaP2t7EXNk2xwdyPZjHvSmqdrB+ApyZNlkJ16//nXZJrBWgqk0Z7B32Ow7Nx6q4dWe6uBzoLv9X5qKEi9GfhEde/0VRLG3j7er/7tL0DOFFbo4GGFre5krw7TJ2d2f9EETy2LN4xxAm+f+BVxHOTOprTz7pmI472yAup20VrPm4YRkrCYOmFfYjFdMNa+Tbya/SLkvwTDWElk0QPZ+VYiv49N9NnGv4QM7N9kuBmGqY9z4WnINpuHA54fasBn8+ypnbK1CK8lbJUQbBsdMLieUTdTCc2xaxsDMR/QS5/iH2nQX98NfPJWZkZ4IZvqK5Bv+50hJUlBZGol+Qu+36+q6y3T7DDVz+PmWPdNA3o0gJyPmxnV/nYdV1q2SofovZBfeWwrNWt2xzTW3H+nx/aBZdZU9nUtvPUkBzoKtpSzUhtSTyysEU6Z+yymWW0xdmqASUckG5rjsjfXgCevbVOx9n/BZwQ8w4eOKB9lnrljagYVBfj77Gcgh3i69n38O+Bf9frqA=
      skip_cleanup: true
      file_glob: true
      file:
        - bakelite-*.tar.gz
        - sha512sum.txt
      on:
        tags: true
